/* Credentials & integration (plan T-2 / I-10) — client ID per environment, reveal-once secret, key pair,
   IP allowlist, sandbox tester and API docs. KHDA IT issues and rotates (Administrator); institutions see
   status, last-used and can request allowlist changes. */
(function () {
  'use strict';
  const K = window.KHDA_SECTOR, R = window.KHDA_ROLES;
  const $ = s => document.querySelector(s);
  const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const params = new URLSearchParams(location.search);
  const role = R.role();
  let inst = role.team === 'inst' ? K.own() : (K.INSTITUTIONS.find(i => i.id === params.get('inst')) || null);
  let env = 'production';
  const hex = (s, n) => (K.hash(s).toString(16) + K.hash(s + 'x').toString(16) + K.hash(s + 'y').toString(16)).slice(0, n);

  function renderList() {
    $('#main').innerHTML = `
      <div class="page-head"><div><div class="page-head__eyebrow">KHDA IT · Security</div><h1 class="page-head__title">Institution credentials</h1><p class="page-head__sub">Client IDs, secrets, keys and IP allowlists per environment. Issue, rotate, suspend, revoke — never edit in place.</p></div>
        <div class="page-head__actions"><a class="btn btn--outline" href="remediation.html?view=technical">Technical failures</a><button class="btn btn--primary" type="button" id="issueNew" data-tier="administrator">＋ Issue client ID</button></div></div>
      <div class="kpi-grid"><div class="kpi kpi--success"><div class="kpi__label">Production clients</div><div class="kpi__value">${K.INSTITUTIONS.filter(i => i.wave <= 2).length}</div><div class="kpi__note">active</div></div><div class="kpi kpi--info"><div class="kpi__label">Sandbox clients</div><div class="kpi__value">${K.INSTITUTIONS.length}</div><div class="kpi__note">one per institution</div></div><div class="kpi kpi--warning"><div class="kpi__label">Secrets expiring ≤ 30 d</div><div class="kpi__value">${K.INSTITUTIONS.filter(i => K.hash(i.id + 'exp') % 7 === 0).length}</div><div class="kpi__note">rotation reminders sent</div></div><div class="kpi kpi--error"><div class="kpi__label">Auth failures · 24 h</div><div class="kpi__value">${K.INSTITUTIONS.reduce((n, i) => n + (K.hash(i.id + 'af') % 4 === 0 ? K.hash(i.id) % 9 : 0), 0)}</div><div class="kpi__note">401 / IP rejections at API Hub</div></div></div>
      <section class="panel"><div class="table-wrap" style="border-radius:12px"><table class="data-table data-table--compact"><thead><tr><th>Institution</th><th>Production client</th><th>Sandbox client</th><th>Secret expires</th><th>IP allowlist</th><th>Last used</th><th></th></tr></thead><tbody>
        ${K.INSTITUTIONS.map(i => `<tr><td><div class="cell-title">${esc(i.name)}</div><div class="cell-sub">${esc(i.waveLabel)}</div></td><td>${i.wave <= 2 ? `<span class="cell-code">khda-${esc(i.short.toLowerCase().replace(/[^a-z]/g, ''))}-prod</span> <span class="chip chip--complete">Active</span>` : '<span class="cell-muted">Not issued</span>'}</td><td><span class="cell-code">khda-${esc(i.short.toLowerCase().replace(/[^a-z]/g, ''))}-sbx</span> <span class="chip chip--complete">Active</span></td><td>${K.hash(i.id + 'exp') % 7 === 0 ? '<span class="cell-late">in 12 days</span>' : K.fmtDate(new Date(K.TODAY.getTime() + (60 + K.hash(i.id) % 200) * 86400000))}</td><td>${2 + K.hash(i.id + 'ip') % 3} entries</td><td class="cell-muted">${K.hash(i.id + 'lu') % 5 === 0 ? '3 days ago' : 'today'}</td><td class="actions"><a class="btn btn--text btn--sm" href="credentials.html?inst=${i.id}">Manage →</a></td></tr>`).join('')}
      </tbody></table></div></section>`;
    $('#main').removeAttribute('aria-busy');
    $('#issueNew').addEventListener('click', () => { if (!R.can('administrator')) return window.khdaToast('error', 'Administrator tier required', 'Client IDs are issued by a KHDA IT Administrator.'); window.khdaToast('info', 'Issue client ID', 'Pick an institution row and use Manage →'); });
    R.gate();
  }

  function renderInst() {
    const cid = `khda-${inst.short.toLowerCase().replace(/[^a-z]/g, '')}-${env === 'production' ? 'prod' : 'sbx'}`;
    const hasProd = inst.wave <= 2;
    const ips = Array.from({ length: 2 + K.hash(inst.id + 'ip') % 3 }, (_, i) => `94.20${K.hash(inst.id + i) % 9}.${K.hash(inst.id + 'b' + i) % 250}.${K.hash(inst.id + 'c' + i) % 250}`);
    const it = role.team !== 'inst';
    $('#main').innerHTML = `
      <div class="page-head"><div><div class="page-head__eyebrow">${it ? 'KHDA IT · Credentials' : 'Institution · Integration'}</div><h1 class="page-head__title">${esc(inst.name)}</h1><p class="page-head__sub">${it ? 'Issue, rotate, suspend and revoke. Every change is audit-logged and needs a second approver in production.' : 'Your API access. Secrets are shown once when issued; ask KHDA IT to rotate.'}</p></div>
        <div class="page-head__actions">${it ? `<a class="btn btn--outline" href="credentials.html">← All institutions</a><a class="btn btn--outline" href="onboarding.html?inst=${inst.id}">Onboarding journey</a>` : ''}<div class="env-tabs" role="group" id="envTabs"><button type="button" data-env="sandbox" aria-pressed="${env === 'sandbox'}">Sandbox</button><button type="button" data-env="production" aria-pressed="${env === 'production'}">Production</button></div></div></div>
      ${env === 'production' && !hasProd ? `<div class="alert"><div><div class="alert__title">Production not enabled yet</div><div class="alert__text">${esc(inst.short)} is at touch point ${3 + K.hash(inst.id + 'tp') % 2} of 6. Production credentials are issued after the go-live gate is signed off by a KHDA IT Supervisor. <a href="onboarding.html?inst=${inst.id}">See the journey →</a></div></div></div>` : ''}
      <div class="grid-main-side">
        <section class="panel"><div class="panel__head"><div><h2 class="panel__title">Client credentials · ${env}</h2><p class="panel__sub">Sent with every call through iPaaS → API Hub. Client ID is public; the secret and private key never leave the institution.</p></div></div>
          <div class="cred"><div class="cred__k">Client ID<small>Issued ${K.fmtDate(new Date(K.TODAY.getTime() - (90 + K.hash(inst.id) % 200) * 86400000))} by Ahmed Al Suwaidi</small></div><div class="cred__v">${cid} <span class="chip chip--complete">Active</span></div><div>${it ? `<button class="btn btn--outline btn--sm" type="button" data-tier="administrator" data-act="suspend">Suspend</button>` : '<button class="btn btn--outline btn--sm" type="button" data-copy="' + cid + '">Copy</button>'}</div></div>
          <div class="cred"><div class="cred__k">Client secret<small>Expires ${K.fmtDate(new Date(K.TODAY.getTime() + (60 + K.hash(inst.id) % 200) * 86400000))} · shown once at issue</small></div><div class="cred__v">••••••••••••••••••••${hex(inst.id + env, 4)} <span class="cell-muted">last 4</span></div><div>${it ? `<button class="btn btn--outline btn--sm" type="button" data-tier="administrator" data-act="rotate">Rotate</button>` : '<button class="btn btn--outline btn--sm" type="button" data-act="request-rotate">Request rotation</button>'}</div></div>
          <div class="cred"><div class="cred__k">Institution public key<small>RSA-2048 · registered for request signing</small></div><div class="cred__v">SHA256:${hex(inst.id + 'key', 24)}… <span class="chip chip--complete">Registered</span></div><div>${it ? '<button class="btn btn--outline btn--sm" type="button" data-tier="supervisor" data-act="replace-key">Replace</button>' : '<button class="btn btn--outline btn--sm" type="button" data-act="upload-key">Upload new key</button>'}</div></div>
          <div class="cred"><div class="cred__k">KHDA public key<small>Verify responses and webhooks</small></div><div class="cred__v">SHA256:9f3c…${hex('khda' + env, 8)} <span class="cell-muted">v2026-01</span></div><div><button class="btn btn--outline btn--sm" type="button" data-act="download-key">Download</button></div></div>
          <div class="cred"><div class="cred__k">Token endpoint<small>OAuth 2.0 client credentials</small></div><div class="cred__v">https://api${env === 'sandbox' ? '-sandbox' : ''}.khda.gov.ae/oauth2/token</div><div><button class="btn btn--outline btn--sm" type="button" data-copy="https://api${env === 'sandbox' ? '-sandbox' : ''}.khda.gov.ae/oauth2/token">Copy</button></div></div>
        </section>
        <div style="display:flex;flex-direction:column;gap:24px">
          <section class="panel"><div class="panel__head"><h2 class="panel__title">IP allowlist · ${env}</h2></div>${ips.map((ip, i) => `<div class="receipt" style="grid-template-columns:minmax(0,1fr) auto"><div><div class="cell-title mono">${ip}/32</div><div class="receipt__text">${i === 0 ? 'Primary egress · last seen today' : 'Backup egress · last seen ' + (K.hash(ip) % 20 + 1) + ' days ago'}</div></div>${it ? '<button class="btn btn--text btn--sm" type="button" data-tier="supervisor" data-act="remove-ip">Remove</button>' : '<span class="chip chip--complete">Applied</span>'}</div>`).join('')}<div class="field-row" style="grid-template-columns:minmax(0,1fr) auto"><input class="control" id="newIp" placeholder="Add IPv4 address or CIDR"><button class="btn btn--outline btn--md" type="button" id="addIp" ${it ? 'data-tier="supervisor"' : ''}>${it ? 'Apply' : 'Request'}</button></div><p class="cell-muted">${it ? 'Applied to iPaaS and API Hub within 5 minutes; stale entries are pruned after 90 days unseen.' : 'Requests go to KHDA IT; a Supervisor applies them to iPaaS and the API Hub.'}</p></section>
          <section class="panel"><div class="panel__head"><h2 class="panel__title">Sandbox tester</h2></div><p class="panel__sub" style="margin-top:-12px">Send a signed sample payload for one dataset and watch it move through the journey.</p><select class="control control--select" id="tstDs">${(window.KHDA_DATASETS || []).slice(0, 12).map(d => `<option>${esc(K.titleOf(d))}</option>`).join('')}</select><button class="btn btn--primary btn--md" type="button" id="runTest" ${env === 'production' ? 'disabled title="Tester runs in sandbox only"' : ''}>▶ Send test payload</button><div id="tstOut"></div></section>
          <section class="panel"><div class="panel__head"><h2 class="panel__title">API documentation</h2></div><ul class="spec-rules"><li><a href="#">OpenAPI 3.1 specification · v2026.1</a></li><li><a href="#">Submission endpoint · POST /v1/submissions/{dataset}</a></li><li><a href="#">Receipt & journey · GET /v1/receipts/{id}</a></li><li><a href="#">Error codes · T-401 · T-415 · T-500</a></li><li><a href="rules.html">Validation rules by dataset →</a></li></ul></section>
        </div>
      </div>`;
    $('#main').removeAttribute('aria-busy');
    $('#envTabs').addEventListener('click', e => { const b = e.target.closest('[data-env]'); if (b) { env = b.dataset.env; renderInst(); } });
    $('#main').querySelectorAll('[data-copy]').forEach(b => b.addEventListener('click', () => { try { navigator.clipboard.writeText(b.dataset.copy); } catch { /* ignore */ } window.khdaToast('success', 'Copied', b.dataset.copy); }));
    $('#main').querySelectorAll('[data-act]').forEach(b => b.addEventListener('click', () => {
      const need = b.dataset.tier; if (need && !R.can(need)) return window.khdaToast('error', need.charAt(0).toUpperCase() + need.slice(1) + ' tier required', 'This credential action is restricted.');
      const a = b.dataset.act;
      const msg = { suspend: ['Client suspended', 'Tokens revoked · second approver notified'], rotate: ['New secret issued', 'Shown once: ' + hex(inst.id + Date.now(), 32) + ' · old secret valid 7 days'], 'request-rotate': ['Rotation requested', 'KHDA IT will issue a new secret; you will see it once.'], 'replace-key': ['Key replaced', 'Old key retired · audit logged'], 'upload-key': ['Key uploaded', 'Pending registration by KHDA IT'], 'download-key': ['Downloaded', 'khda-public-' + env + '.pem'], 'remove-ip': ['IP removed', 'Applied to iPaaS and API Hub'] }[a];
      window.khdaToast(a === 'suspend' || a === 'remove-ip' ? 'info' : 'success', msg[0], msg[1]);
    }));
    $('#addIp').addEventListener('click', () => { const v = $('#newIp').value.trim(); if (!/^\d+\.\d+\.\d+\.\d+(\/\d+)?$/.test(v)) return window.khdaToast('error', 'Not an IPv4 address', 'Use a.b.c.d or a.b.c.d/nn'); if (it && !R.can('supervisor')) return window.khdaToast('error', 'Supervisor tier required', 'Allowlist changes are applied by a Supervisor.'); window.khdaToast('success', it ? 'Applied' : 'Requested', v + (it ? ' · live in 5 minutes' : ' · sent to KHDA IT')); $('#newIp').value = ''; });
    $('#runTest').addEventListener('click', () => { const d = (window.KHDA_DATASETS || [])[$('#tstDs').selectedIndex]; const sub = { ...K.submission(inst, d, K.period()), status: 'in_validation', receivedAt: K.TODAY, channel: 'api', inst, dataset: d, issues: [] }; $('#tstOut').innerHTML = `<div class="cell-muted" style="margin:8px 0">Receipt ${'rcpt-' + hex(inst.id + d.sheet, 8)} · 12 rows · signed OK</div>${window.KHDA_JOURNEY.render(sub, { compact: true })}`; window.khdaToast('success', 'Test payload accepted at API Hub', 'Validation running in the sandbox DQ layer'); });
    R.gate();
  }
  if (inst) renderInst(); else renderList();
})();
